### ISSUE TITLE
How to respond to this error ? 

### ISSUE THREAD

**Issue by BobYT2** [member87/cam-finder#9]
File "/home/bob/cam-finder/main.py", line 99, in <module>
    if config.SHODAN:
       ^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'SHODAN'

**Comment by member87** [comment]
have you copied the `example-config.py` file to `config.py`? The config file will need to contain the following values in the example config:
- SHODAN
- CENSYS
- MAX_THREADS
- SHODAN_API (required if `SHODAN` is true)
- CENSYS_API (required if `CENSYS` is true)
- CENSYS_SECRET (required if `CENSYS` is true)

**Comment by BobYT2** [comment]
ok i did it worked thx !
